packages:
  openssl:
    variants: [certs=mozilla]
  slurm:
    externals:
    - spec: slurm@20-11-8-1
      prefix: /usr
  rdma-core:
    externals:
    - spec: rdma-core@39.1
      prefix: /usr
  xpmem:
    externals:
    - spec: xpmem@0.29.2
      prefix: /opt/cray/xpmem/2.2.40-2.1_2.56__g3cf3325.shasta