mirrors:
  url:
    fetch:
      url: file:///scratch/mchstor2/users/bcumming/spack-cache
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
    push:
      url: file:///scratch/mchstor2/users/bcumming/spack-cache
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
