mirrors:
  alpscache:
    fetch:
      url: file:///scratch/e1000/meteoswiss/scratch/bcumming/build-cache/mch-environment/devt
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
    push:
      url: file:///scratch/e1000/meteoswiss/scratch/bcumming/build-cache/mch-environment/devt
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
