# -------------------------------------------------------------------------
# This is the default configuration for Spack's module file generation.
#
# Settings here are versioned with Spack and are intended to provide
# sensible defaults out of the box. Spack maintainers should edit this
# file to keep it current.
#
# Users can override these settings by editing the following files.
#
# Per-spack-instance settings (overrides defaults):
#   $SPACK_ROOT/etc/spack/modules.yaml
#
# Per-user settings (overrides default and site settings):
#   ~/.spack/modules.yaml
# -------------------------------------------------------------------------
modules:
  # Paths to check when creating modules for all module sets
  prefix_inspections:
    bin:
      - PATH
    lib:
      - LD_LIBRARY_PATH
    lib64:
      - LD_LIBRARY_PATH

  # These are configurations for the module set named "default"
  default:
    arch_folder: false
    # Where to install modules
    roots:
        tcl: /user-environment/modules 
    # What type of modules to use
    enable:
      - tcl
    tcl:
      hash_length: 7
      naming_scheme: '${PACKAGE}/${VERSION}-${COMPILERVER}'
      all:
        autoload: none
